### ISSUE TITLE
Setup: Installed config needs to be updated when structure changes

### ISSUE THREAD

**Issue by GeneCupstid** [LogRhythm-Tools/LogRhythm.Tools#12]
## Expected Behavior
Scenario: 
- User has LRT installed w/ config in place
- New release that includes changes to config `LogRhythm.Tools.json`
- When new version is installed, the two are merged or otherwise updated with the new structure
- Previous values are retained?

## Actual Behavior
Currently the existing configuration in LocalAppData is not changed at all.

## Steps to Reproduce the Problem
1. Make a new section to `LogRhythm.Tools.json`
2. Run from `tests\Lrt.Publisher\Test-LrtPublish.ps1`
3. Setup will fail to update configuration because the old version wasn't updated.

```
The property 'DomainName' cannot be found on this object. Verify that the property exists and can be set.
At C:\repos\_community\LogRhythm.Tools\tests\Lrt.Publisher\data\lrt-install\Setup.ps1:202 char:17
+ ...             $LrtConfig.($ConfigCategory.Name).($ConfigField.Name) = $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
```

**Comment by Jt3kt** [comment]
What are approaches you are considering for this?  

I would look at this type of logical flow:

1. Check for existing LogRhythm.Tools.json
  a. If it does not exist, proceed on to setup
2.  Load existing LogRhythm.Tools.json as object
3.  Step through each section of the configuration file's properties comparing the field name
   a.  Ie, Verify all record property names under LogRhythm -> Version, Platform Manager, APIKey, etc
4. If new property names are found, we know we need to update the existing preference files structure
5.  Rinse & repeat for each root preference object.  We can check for new root objects via object count as well.  

The goal would be to capture changes made inside of established properties as well as identifying new sections added.  In the event we find a new object, pre-seed the existing values into the structure of the new configuration file and replace the file at the appropriate point of the setup process.

**Comment by Jt3kt** [comment]
Added in a first round solution to this issue.  This mitigates the bug by enabling the last config to be applied to a new config structure.  This method can be matured but is a working model to test with to identify any issues.
