### ISSUE TITLE
Case: Include Playbooks in default Case Object?

### ISSUE THREAD

**Issue by GeneCupstid** [LogRhythm-Tools/LogRhythm.Tools#20]
Should we build a more complete Case object?  Include Playbooks, Notes, etc?

**Comment by Jt3kt** [comment]
Can you show an idea of what you're thinking?

Retrieving case details via Get-LrCasebyId should only return the data from the /cases/$CaseNumber/ endpoint.

I do agree a helper function should be created that combines API calls to retrieve all data associated to a case and structure that as an object.  To support that we need to create a few new cmdlets.

Retrieval of change log made to case.
Retrieval of evidence from case: Notes, Alarms, Files, Logs

From there the output of the retrieve full case details can be applied to reporting, exporting, etc.

**Comment by Jt3kt** [comment]
This request is accomplished by New-LrCaseHelper, a function that aligns multiple LogRhythm API functions into the action of creating a LogRhythm Case.

This function exists in the branch: dev-1.0.1-CaseHelpers.  

Supports:
Case creation
Add Case tag
Add Playbook to case
Case Summary

AIE Cache Drilldown
  Determine Case Priority based on Alarm Risk Rating

Toggle Flags to enable Case Tag Creation from drilldown based on: 
  User Origin
  User Impacted
  Host Origin
  Host Impacted
