### ISSUE TITLE
Setup: Workaround when Get-LrInstallerInfo can't find install scope paths

### ISSUE THREAD

**Issue by GeneCupstid** [LogRhythm-Tools/LogRhythm.Tools#4]
## Overview

Install Scope is used as the path to where modules are installed for the system.

- User Scope: $HOME + Documents\WindowsPowerShell\Modules
- System Scope: $PSHOME or $Env:ProgramFiles - typicall t

## Option 1

Update `Install-Lrt` to prompt the user for an install location if the standard install scope path can't be found.  

## Option 2

Update `Setup.ps1` to accept a custom module install location which is then passed to `Install-Lrt` as a parameter.

**Comment by GeneCupstid** [comment]
Related to this, I've found that there can be problems when a machine is configured to map user drives to a network location.  More research needed, but recommending either manual or system install for these scenarios right now.

**Comment by Jt3kt** [comment]
Coded a resolution for re-mapped user drives by leveraging this means of identifying the user's MyDocuments:
`$([Environment]::GetFolderPath('MyDocuments'))`

This is a reference as provided by Microsoft.  

This is a part of commit c8b8ea489a71d48bb190cb5c51e5343eed5345bf that covers installation of the module with PS Core.
