### ISSUE TITLE
LrtConfig: DX Nodes

### ISSUE THREAD

**Issue by Jt3kt** [LogRhythm-Tools/LogRhythm.Tools#43]
**Is your feature request related to a problem? Please describe.**
Expand the LrtConfig to permit the optional addition of DX Cluster(s).  At the install/re-configure of LogRhythm.Tools the user should be able to prompted to configure DX environment.  I do recommend we put in place step in the LogRhythm setup for L.rTools for Advanced or Basic as expanding into the direction this configuration is intended to support is for Advance use cases only.

The installer should have the ability to dynamically scale/set the LogRhythm.Tools.json based on the installing user's provided input for DX to reduce bloat and keep the config focused on relevant enabled content.

**Describe the solution you'd like**
Expand the LogRhythm config to permit the following structure example:

```    
"LogRhythm": {
        "Version":"7.5.0",
        "AdminBaseUrl": "https://[NOT_SET]:8501/lr-admin-api",
        "CaseBaseUrl": "https://[NOT_SET]:8501/lr-case-api",
        "AieBaseUrl": "https://[NOT_SET]:8501/lr-drilldown-cache-api",
        "SearchBaseUrl": "https://[NOT_SET]:8501/lr-search-api",
        "ApiKey": "",
	"DX": {
		"Cluster1": {
			"Health": "",
			"Master": "",
			"Open": "",
			"Closed": "",
			"Zones": {
				"Zone1": "",
				"Zone2": ""
			}
			"Node1": {
				"Hostname": "",
				"IPAddress": "",
				"2xDx": false,
				"WarmNode": false,
				"Zone": ""
			},
			"Node2": {
				"Hostname": "",
				"IPAddress": "",
				"2xDx": false,
				"WarmNode": false,
				"Zone": ""
			},
			"Node3": {
				"Hostname": "",
				"IPAddress": "",
				"2xDx": false,
				"WarmNode": false,
				"Zone": ""
			}
		},
		"Cluster2": {
			"Health": "",
			"Master": "",
			"Open": "",
			"Closed": "",
			"Zones": {
				"Zone1": "",
				"Zone2": ""
			}
			"Node1": {
				"Hostname": "",
				"IPAddress": "",
				"2xDx": false,
				"WarmNode": false,
				"Zone": ""
			},
			"Node2": {
				"Hostname": "",
				"IPAddress": "",
				"2xDx": false,
				"WarmNode": false,
				"Zone": ""
			},
			"Node3": {
				"Hostname": "",
				"IPAddress": "",
				"2xDx": false,
				"WarmNode": false,
				"Zone": ""
			}
		},
		"Cluster3": {
			"Health": "",
			"Master": "",
			"Open": "",
			"Closed": "",
			"Zones": {
				"Zone1": "",
				"Zone2": ""
			}
			"Node1": {
				"Hostname": "",
				"IPAddress": "",
				"2xDx": false,
				"WarmNode": false,
				"Zone": ""
			},
			"Node2": {
				"Hostname": "",
				"IPAddress": "",
				"2xDx": false,
				"WarmNode": false,
				"Zone": ""
			},
			"Node3": {
				"Hostname": "",
				"IPAddress": "",
				"2xDx": false,
				"WarmNode": false,
				"Zone": ""
			}
		}
	}
}
```

**Additional context**
The primary goal of this will be to expand into advance DX management to support controlled automated rolling restarts, troubleshooting, and applying advance DX configuration(s).

**Comment by GeneCupstid** [comment]
Since this is a large enough feature all dedicated to a single part of LR, we could probably implement this as a new file.  Will need to discuss how this will work.

I'm wondering if there's a way we can detect the configuration... I don't do much with indexers.  The indexers know about each other, right?  Or that info is in the LR database?  We could perhaps tap into that and extract / build the config somehow.

**Comment by jberkers42** [comment]
We do quite a bit with indexers, and outside of LR some additionan stuff with ElasticSearch generally as well.

Querying the DX Cluster for information requires that whereever you are running the commans from requires access to port 9200 on at least one of the ElasticSearch nodes.  By default the LR installer locks this down to only being accessible inside the DX Clluster itself.

For our own reasons, we have opened port 9200 up to at least the remainder of the LR Deployment, and in some cases a Jump Host from which we perform most of our management.  So we don't have an issue there ourselves, however, this would require some instructions/assistance for users to alter the Linux Firewall configuration on a dedicated DX/Cluster.

Once you have access you can use the /_nodes endpoint to get details about each node in JSON format.

```json
{
    "_nodes": {
        "total": 14,
        "successful": 14,
        "failed": 0
    },
    "cluster_name": "vhmpdx",
    "nodes": {
        "XusrK4zhTBGCIo_FGBqGlg": {
            "name": "vhmpdxh01",
            "transport_address": "10.6.8.181:9300",
            "host": "10.6.8.181",
            "ip": "10.6.8.181",
            "version": "6.8.3",
            "build_flavor": "oss",
            "build_type": "rpm",
            "build_hash": "0c48c0e",
            "total_indexing_buffer": 3820455198,
            "roles": [
                "master",
                "data",
                "ingest"
            ],
            "attributes": {
                "box_type": "hot"
            },
            "settings": { "data": "****** Stuff omitted for brevity ******"}
        }
    }
}
```

There's quite a lot more information available for each node.

Additionally, you can also get catalog information about how many indices, hot, warm, etc. As well as potentially showing information about Restored Archive indices and related information.

There is no authentication required, so I would caution against opening up port 9200 on the indexers too widely.

I've already done a bunch of work with PowerShell and ElasticSearch, so can probably contribute some stuff here if desired.

Regards,

JohnB

**Comment by Jt3kt** [comment]
Removing DX from Lr.Tools project scope.  DX resources will likely be self-sufficient and available separate from the LR.Tools PowerShell module resource.
