### ISSUE TITLE
Update Setup.ps1 to support handling LogRhythm Cloud

### ISSUE THREAD

**Issue by Jt3kt** [LogRhythm-Tools/LogRhythm.Tools#48]
## Expected Behavior
When setting up LR.Tools for LogRhythm cloud the schema in the LR.Tools.json needs to be updated.

LogRhythm Cloud's API endpoints are available over TCP port 443 and not over 8501.

## Actual Behavior
Adding in the URL's for a LogRhythm Cloud endpoint creates:
https://URLforLogRhythmCloud.cloud:8501/endpoint/

Recommended fix:
Inspect the provided URL based on regex for the url.cloud and when that is applied seed in the LR.Tools.json config to align to schema:
https://URLforLogRhythmCloud.cloud/endpoint/

## Specifications

  - Version: Any
  - Platform: LogRhythm Cloud
  - Subsystem: LogRhythm.Tools 1.0.0

**Comment by GeneCupstid** [comment]
@Jt3kt  I could make this so much more interactive and capable of more complex entry / update if I could do this in c#.  The source code would be on the website, of course.  

Also, now that we've "released" and presented at RW, would LogRhythm be willing to donate the funds to purchase a code signing certificate for the project?  It wouldn't be in their name, they would just cover the cost of obtaining one.  A pretty cheap price for what they're getting - $100 or less.  :)

**Comment by Jt3kt** [comment]
Easy enough to accomplish without going to C#.

**Comment by Jt3kt** [comment]
Updated dev 1.0.1 branch with updated cmdlets to support defining custom Port on the Get-InputApiUrl.  If a port is not provided, the existing value will remain.  If there is no port existing in the current value and a new one is added, it will be appended to the URL string.  

Added new special character permitted on Setup.ps1's Remove-SpecialChars as leveraged on reading in user's input for value submission.
