### ISSUE TITLE
Handling LogRhythm API 429 Errors

### ISSUE THREAD

**Issue by GeneCupstid** [LogRhythm-Tools/LogRhythm.Tools#50]
## Requirement
All LR cmdlets should support rate limiting to throttle requests should the LR API return HTTP 429.  As commands are frequently combined via the pipeline, it is possible for any of the LR cmdlets that access the RestAPI to trigger such an error.

For Example, this is a 429 received by Get-LrCaseById as a result of calling Get-LrCases

```
> $July[300].Metrics

LookupType : CaseNumber
IsValid    : False
Value      : 3833
CaseNumber :
CaseName   :
CaseGuid   :
Note       : Rate Limit Exceeded
```

## Milestone
Include in 1.0.1 as a fix for this issue

## Detail

This issue pops up primarily in the metrics commands, because it works like this:

1. `Get-LrCases`: Rest Request to `/cases/`
2. `Get-LrCaseMetrics`: receives the Case ID via pipeline, and needs to test it with `Test-LrCaseIdFormat`, which hits the API
3.  `Get-LrCaseMetrics: Rest Request to `/cases/$CaseNumber/metrics`

That's three requests for each request returned by `Get-LrCases`, and when you pull a couple hundred cases or so, the rate limit of the API will be triggered.

**Comment by Jt3kt** [comment]
Built handler for HTTP 429 into LogRhythm.Tools via the private cmdlet Invoke-RestAPIMethod that has a specific means to handle the HTTP 429 rate limit reached for all LogRhythm API calls.
