### ISSUE TITLE
Case Status Parameters should use ValidateSet

### ISSUE THREAD

**Issue by GeneCupstid** [LogRhythm-Tools/LogRhythm.Tools#59]
Validate Set for the values below anywhere a Case Status Parameter is used.

- Created
- Completed
- Incident
- Mitigated
- Resolved

Validate set for values below anywhere a Procedure Step Status Parameter is used.

- Completed
- NotCompleted

**Comment by Jt3kt** [comment]
Added in parameter validation set for Update-LrCaseStatus and Get-LrCaseStatusTable.  

The Update-LrCasePlaybookProcedure had an existing appropriate restriction for the following values:
'NotCompleted', 'Completed', 'Skipped'
