### ISSUE TITLE
New-TestBuild: Re-Implement for development purposes

### ISSUE THREAD

**Issue by GeneCupstid** [LogRhythm-Tools/LogRhythm.Tools#6]
## Overview
We used to have a script called `New-TestBuild` that would make it easier for developers to re-load the LogRhythm.Tools module with the changes they've made.  This was lost when the updated/new Lrt.Builder and Lrt.Installer modules were developed.

## Solution
Re-implement `New-TestBuild` for the current generation of the project.

**Comment by GeneCupstid** [comment]
While developing this, a bug was discovered in the module's `psm1` file.  Bug related to how the API keys are imported by `psm1`, and keys were being loaded multiple times due to an unnecessary nested `for` loop.

**Comment by GeneCupstid** [comment]
@Jt3kt - the `development` branch has the fixes for `New-TestBuild`.  You can run the script directly without parameters the way you'd expect.

The one requirement is that `Setup.ps1` has been run at least once on the host, so that the configuration infrastructure is in place (or you can manually copy the config to `%LocalAppData%\LogRhythm.Tools`.

The `-RemoveOld` tag will clean up your `debug` directory of old builds.

**Comment by Jt3kt** [comment]
This worked on my initial test.  Going to put it through some additional use.

**Comment by Jt3kt** [comment]
So far all has been great with the new-testbuild function.  No issues encountered on two systems I'm working with.

**Comment by GeneCupstid** [comment]
Working well for me too, closing issue.
