### ISSUE TITLE
MessageSourceTypeId to Get-LrLogSources not used in search

### ISSUE THREAD

**Issue by timbrigham** [LogRhythm-Tools/LogRhythm.Tools#60]
## Expected Behavior
Lookups to Get-LrLogSources should allow lookups with the flag -MessageSourceTypeId xxxx and return specific results

## Actual Behavior
All log sources are returned. 

## Steps to Reproduce the Problem
```
Get-LrLogSources -MessageSourceTypeId "12345" -verbose

VERBOSE: [Enable-TrustAllCertsPolicy]: Cert Policy is not enabled. Enabling.
VERBOSE: []: QueryString is [?count=1000&offset=0&recordStatus=active]
VERBOSE: GET https://xx:8501/lr-admin-api/logsources/?count=1000&offset=0&recordStatus=active with 0-byte
payload
VERBOSE: received -1-byte response of content type application/json
VERBOSE: [Enable-TrustAllCertsPolicy]: Cert Policy is not enabled. Enabling.
VERBOSE: []: QueryString is [?count=1000&offset=1000&recordStatus=active]
VERBOSE: GET https://xxx:8501/lr-admin-api/logsources/?count=1000&offset=1000&recordStatus=active with 0-byte
 payload
VERBOSE: received -1-byte response of content type application/json
VERBOSE: [Enable-TrustAllCertsPolicy]: Cert Policy is not enabled. Enabling.
VERBOSE: []: QueryString is [?count=1000&offset=2000&recordStatus=active]
VERBOSE: GET https://xxx:8501/lr-admin-api/logsources/?count=1000&offset=2000&recordStatus=active with 0-byte
 payload
VERBOSE: received -1-byte response of content type application/json

```

## Specifications

  - Version: 1.0.0

**Comment by Jt3kt** [comment]
Thanks @timbrigham, I'll plan to investigate this when I revisit the admin/logsource APIs. 

Good catch.

**Comment by Jt3kt** [comment]
Hey @timbrigham, 

Looks like the majority of the API endpoint filters were not coded into the function in its initial release revision.  I've updated the cmdlet to support -MessageSourceTypeId as well as the additional methods supported by the API for result filtering.

I'm marking this issue closed as the fix is applied and will be incorporated in our next packaged release.
