### ISSUE TITLE
Get-LrLists returns a mix of Retired + Active lists

### ISSUE THREAD

**Issue by jberkers42** [LogRhythm-Tools/LogRhythm.Tools#79]
**Is your feature request related to a problem? Please describe.**

When working with LogRhythm Lists, it is possible for lists with Duplicate Names to exist where both Active and Retired lists are present.  The default behaviour for Get-LrLists would preferably only return Active Lists, and only return Retired Lists when specifically requested.

**Describe the solution you'd like**

An added option on the CmdLet to return retired lists when requested would be the preferred solution.  This woudl also be in line with behaviour in both LogRhythm Console as well as the Web UI.

**Describe alternatives you've considered**

Alternatives are to ensure that every list name is unique (for both active and retired lists), and to specify ExactMatch when only one list is desired.

**Additional context**

This specifically tied in with the Recorded Future functionalith in which it updates lists.  I encountered an issue with automation, where I use the Invoke-RfSync, which created lists, then I imported AIE rules from another platform, which also created the same lists, with the same names (some truncated).

**Comment by GeneCupstid** [comment]
Great point @jberkers42!  I'll take this one.

**Comment by Jt3kt** [comment]
Corrected this behavior in commit ba0901c74bb0310e8891f56c6d76c521143ee988.  This is an enhancement and not a bug; the RestAPI does not support this functionality so this has been added in as an enhancement logic through the cmdlet.  #
