### ISSUE TITLE
List Update should retry when SQL Transaction Deadlock is encountered

### ISSUE THREAD

**Issue by jberkers42** [LogRhythm-Tools/LogRhythm.Tools#80]
## Expected Behavior

When Update-LrList calls the API and gets an SQL Transaction Deadlock error, it should retry (up to max retries).

## Actual Behavior

When Update-LrList calls the API and gets an SQL Transaction Deadlock error the list is not updated with new values.

## Steps to Reproduce the Problem

This problem is somewhat intermittent, and dependent on overall platform performance.

  1. Execute an Invoke-RfSync several times on a production system to induce the problem, perhaps concurrently from two shells.
  1. Alternatively, execute an update of the same list using Update-LrList simultaneously using two shells.

## Specifications

  - Version: 1.2.2
  - Platform: LogRhythm 7.7.0
  - Subsystem: Admin/Lists

## Output from error:

```log
[07/14/21 09:13:41] - Updating List: RF : IP : ConfLo : Phishing Host
Invoke-RestMethod: F:\Installers\LogRhythm\LogRhythm.Tools\build\debug\d45d613f-b7bb-4478-b811-ac79fd4c8e15\1.2.1\Public\LogRhythm\Admin\Lists\Update-LrList.ps1:427
Line |
 427 |  … $Response = Invoke-RestMethod $RequestUrl -Headers $Headers -Method $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"statusCode":500,"message":"mssql: Transaction (Process ID 123) was deadlocked on lock resources with
     | another process and has been chosen as the deadlock victim. Rerun the transaction."}
```

**Comment by Jt3kt** [comment]
Hey @jberkers42,

I think with the current implementation of HTTP 429 response handler that the same approach could be applied here.

The caution is that a 500 response by itself is pretty generic so we'll need to scrape the response message and confirm the reason aligns to an appropriate retry.

In your encountering of this issue, do you know what the typical wait period is? 

Would a half-second wait be enough in between the API requests?

Jt3kt

**Comment by jberkers42** [comment]
Hi @Jt3kt ,

I cannot speak for when I encounter issues when using the API, as I have typically not retried it since it is being executed in a script.

We do, on occasion, encounter similar Dealock issues in the Console Client, at which point we usually re-try immediately.  Most of the time this works, however, sometimes it takes 2 or 3 retries. While it is difficult to estimate what the retry interval is when we encounter the issue in this way, it would be no more than a couple of seconds.

How about a default of half a second, with an option to specify a larger value?  Not sure off the top of my head how much more difficult that might be to achieve.

jberkers42
