### ISSUE TITLE
Include RuleBlockId on DrilldownSummary and DrillDownResult.SummaryFields

### ISSUE THREAD

**Issue by jberkers42** [LogRhythm-Tools/LogRhythm.Tools#81]
**Is your feature request related to a problem? Please describe.**
In processing the results from the AIE Drilldown Cache API, LogRhythm.Tools removes the Rule Block identifier from the Summary Fields.  This precludes formatting the resulting data in a fashion similar to what is provided the LR Web Console as there is no indication which rule block each summary came from.

**Describe the solution you'd like**
If the RuleBlockId is included in the Get-AieDrillDownResults.SummaryFields as well as in Get-AieDrillDownSummary then the resulting information can be formatted/presented in a similar way to the Web Console Inspector.

**Describe alternatives you've considered**
Re-summarising the DrilldownLogs provided in the Get-AieDrilldownResults is challenging to achieve the same results, and essentially re-performs the work already performed by the AIE Cache Drilldown Service.

**Additional context**
The following screenshot is representative of the type of information presented in the WebConsole:

![alarm-ruleblocksummary](https://user-images.githubusercontent.com/7709917/136719963-09bdc962-39af-49bf-a636-eab60e76a03d.png)

**Comment by jberkers42** [comment]
In examining the processing code in the functions, I also noted that the data structure is presented differently between the two functions:

* Get-LrAieDrillDown
* Get-LrAieSummary

The LR API returns that data in different manners, depending on the endpoint being called:

* lr-drilldown-cache-api/{id} returns PIFType Ids
* lr-drilldown-cache-api/{id}/summary returns LogRhythm internal field names

So some difference can be expected.

Can the results for SummaryFields be presented consistently for more consistent handling of results?

**Comment by Jt3kt** [comment]
Code is added into the 1.3.0 base and will be made available going forward.
