### ISSUE TITLE
Test-ValidIPv4Address function does not return false when IP address is IPv6

### ISSUE THREAD

**Issue by jberkers42** [LogRhythm-Tools/LogRhythm.Tools#96]
## Expected Behavior

When an IPv6 address is passed to Test-ValidIPv4Address, the function should return $false.

## Actual Behavior

When an IPv6 address is passed to Test-ValidIPv4Address, the function returns $true, even though it is not a valid IPv4 address.

## Steps to Reproduce the Problem

  1. Import-Module LogRhythm.Tools
  1. Test-ValidIPv4Address -IP '2406:da1c:20f:2f00::'
  1. Returns $true

## Specifications

  - Version: LogRhythm.Tools 1.3.2, independent of LogRhythm version
  - Platform: Windows(Desktop and Core), Mac, Linux
  - Subsystem: General

The impact of this is that when performing a Find-LrNetworkByIP, and certain IPv6 networks are defined, these networks are matched incorrectly as only the last 4 "octets" of the IPv6 address are used in the comparison, frequently being between 0 and 4294967295.

**Comment by Jt3kt** [comment]
Mind giving my proposed solution here a review @jberkers42?
