### ISSUE TITLE
New-LRList Throws Exception Around Invalid Owner ID in Request Body

### ISSUE THREAD

**Issue by jandrusk** [LogRhythm-Tools/LogRhythm.Tools#98]
## Expected Behavior
Calling New-LRList should create the requested list specified by -name property.

## Actual Behavior
Bad request exception is throw that states, "{"statusCode":400,"message":"Invalid owner id available in request body."}"

## Steps to Reproduce the Problem

  1. New-LrList -name AndruskList -ListType Host -Owner 2
  
## Specifications

  - Version: 1.3.2
  - Platform: Windows 10 21H2
  - Subsystem: Powershell 5.1

**Comment by Jt3kt** [comment]
Hey @jandrusk,

What happens if you do not supply the -Owner 2 on the Cmdlet call? 

In version 1.3.2 it was coded to use the API token's Owner ID# as the default for the Owner for the created list.  This was to mitigate the issue where typically only the API Key owner can create a list for itself, not assign someone else as the owner.

Thank you,
Eric

**Comment by jandrusk** [comment]
@Jt3kt If I leave off the -Owner parm, it errors out with the same error code. The API key is tied to the lrcloudadmin username, which has a UID of 2.

**Comment by Jt3kt** [comment]
I tested this on my environment and I was able to create lists without setting the owner.

If you run this with -verbose can you provide a summary of the JSON body that is posted to the endpoint?  

Do this without providing the -Owner parm.

**Comment by jandrusk** [comment]
This is the output produced with adding the '-verbose' flag:

VERBOSE: GET https://********.logrhythm.cloud/lr-admin-api/lists/ with 0-byte payload
VERBOSE: received 2-byte response of content type application/json
VERBOSE: [New-LrList] Request Body:
{"listType":"Host","status":"Active","name":"OSBadDomainsList","guid":null,"shortDescription":"","longDescription":"","autoImportOption":{"enabled":false,"usePatterns":false,"replaceExisting":false},"importFileName":"","readAccess":"Publi cGlobalAnalyst","writeAccess":"PublicGlobalAdmin","restrictedRead":false,"entityName":"Primary Site","needToNotify":false,"doesExpire":false,"owner":0}
VERBOSE: POST https://*******.logrhythm.cloud/lr-admin-api/lists/ with -1-byte payload


Request : Invoke-RestMethod
Reason  : WebException
Code    : 400
Error   : True
Type    : BadRequest
Note    : Bad request.  Validate request data and/or API services.
Origin  : New-LrList
Raw     : {"statusCode":400,"message":"Invalid owner id available in request body."}

**Comment by jandrusk** [comment]
@Jt3kt Any ideas how to get around this issue/error?

**Comment by jandrusk** [comment]
``@Jt3kt I decided to run it again just for kicks and the output was giving me different errors about missing parameters.  I ended up modifying the syntax to:

`New-LrList -name ADList1 -ListType Host -TimeToLiveSeconds 1200 -EntityName "United States"`

Which is now producing the error:

```
Body    : {"listType":"Host","status":"Active","name":"ADList1","guid":null,"shortDescription":"","longDescription":"","autoImportOption":{"enabled":false,"usePatterns":false,"replaceExisting":false},"importFileName":"","readAccess":"Publ
          icGlobalAnalyst","writeAccess":"PublicGlobalAdmin","restrictedRead":false,"entityName":"United States","needToNotify":false,"doesExpire":false,"owner":56,"timeToLiveSeconds":1200}
Raw     : {"statusCode":400,"message":"Invalid Read permission"}

```
I tried to see if there was an existing account with UID 56, but there isn't any.

**Comment by jandrusk** [comment]
Got it to work with this syntax:

`New-LrList -name ADList1 -ListType generalvalue -TimeToLiveSeconds 1200 -EntityName "United States" -UseContext "URL" -ReadAccess publicall -WriteAccess publicall`

The key was setting both the 'ReadAccess' & 'WriteAccess' parms to 'publicall'.

**Comment by Jt3kt** [comment]
Copy that @jandrusk.  Explains a bit why I wasn't reproducing but I've noted your observations here.  I think this cmdlet can be improved to make using it more consistent and easier.
